apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: gameservice-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: gameservice
  minReplicas: 1
  maxReplicas: 15
  targetCPUUtilizationPercentage: 50