name: Vue frontend

on:
  push:
    branches: [ "main", "development" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - name : Cache
      uses: actions/cache@v2
      with:
        path: "frontend/node_modules"
        key: node-modules-${{ hashFiles('frontend/package.json') }}
    - run: npm ci
      working-directory: ./BingoBlitz-Frontend
    - run: npm run build --if-present
      working-directory: ./BingoBlitz-Frontend
    - run: npm test
      working-directory: ./BingoBlitz-Frontend
