name: Vue frontend

on:
  push:
    branches: [ "main", "development" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v3
      - name: Execute Unit tests
        working-directory: ./BingoBlitz-Frontend
        run: |
          npm ci
          run: npm run test
